### ISSUE TITLE
Ansible role in ansible galaxy no longer works in Ubuntu Precise 

### ISSUE THREAD

**Issue by ricardoekm** [basho-labs/ansible-riak#11]
Riak doesn't starts. Riak role version: v1.0.9. Riak common version: v1.1.0, Riak version 1.4

TASK: [basho.riak | start riak] *********************************************** 
failed: [186.234.246.54] => {"failed": true}
msg: sudo: unable to resolve host riak-57ebaa2d-dd52-41cb-8bc4-6fe458c4a701
Error on line 18: syntax error before: '<'
Error reading /etc/riak/app.config

The app.config file in ansible-galaxy, differs from the one in github:

Ansible-galaxy:
{pb_backlog, (< riak_pb_backlog >)}

Github:
{pb, [ {"{{ riak_pb_bind_ip }}", {{ riak_pb_port }}} ]}
https://github.com/basho/ansible-riak/blob/develop/templates/etc_riak_app.config.j2

**Comment by christophermancini** [comment]
This fix has been merged into the latest release on Ansible Galaxy.
