### ISSUE TITLE
Version '1.4.10-1' for 'riak' was not found [JIRA: TOOLS-88]

### ISSUE THREAD

**Issue by sujaymansingh** [basho-labs/ansible-riak#16]
I keep getting this when I use the role to install riak.

```
TASK: [basho.riak | install riak] ********************************************* 
failed: [crawler_stats] => {"failed": true}
stderr: E: Version '1.4.10-1' for 'riak' was not found

stdout: Reading package lists...
Building dependency tree...
Reading state information...

msg: 'apt-get install 'riak=1.4.10-1' ' failed: E: Version '1.4.10-1' for 'riak' was not found


FATAL: all hosts have already failed -- aborting
```

How can I use the role to install riak? I have this in my playbook. It is an ubuntu 14.04 box.

```
  - role: basho.riak
    tags: ["riak"]
    sudo: yes 
```

**Comment by christophermancini** [comment]
@sujaymansingh We just released an update to the role. If you are still having issues, please reopen this  ticket and we will check it out for you.

**Comment by sujaymansingh** [comment]
Thanks @christophermancini 
I shall try this.

**Comment by Basho-JIRA** [comment]
Release 1.4.10 was not released as OSS. 

***[posted via JIRA by Derek Somogyi]***
