### ISSUE TITLE
Role overwrites /etc/rc.local -- this is not good behaviour

### ISSUE THREAD

**Issue by TJC** [basho-labs/ansible-riak#20]
If riak_tune_disks is enabled, then /etc/rc.local gets completely overwritten.

I don't think this is good behaviour at all -- sysadmins may have, quite reasonably, added customisations to this file already.

## First suggestion

My suggestion would be to, instead, create an upstart job that starts on boot and runs once, which has the same content as the riak rc.local. That's unfortunately a bit distro-specific; you'd probably need to replicate this work for sysv and systemd as well. I'd say it's the right way to do this, though...

## Alternative suggestion

Install an executable script somewhere with the actual content that current goes in rc.local. Then add a line to /etc/rc.local to call it. This can be done with the "lineinfile" command in Ansible, to just append the line to the file if it doesn't exist, rather than clobbering the whole file.

Thoughts?

**Comment by jsmartin** [comment]
Your alternative is the way to go.

**Comment by christophermancini** [comment]
This was a component that was carried over from the previous version of this role and tbh, I have very little expertise here. If @jsmartin feel that his "Alternative suggestion" is the best route, then I will test Pull Request #24 and accept it.
