### ISSUE TITLE
README.md refers a missing `examples/` folder

### ISSUE THREAD

**Issue by jlbribeiro** [basho-labs/ansible-riak#31]
I was looking for examples regarding the usage of this role to form a cluster and the documentation refers and links a missing `examples/` folder, apparently deleted by cf5d68e46da566bd3e718c22e5eb2645c5b57db5. Because of the commit message I'm not sure if the deletion occurred by mistake, although I'm assuming they were deleted because they were out-of-date; what makes me question this is that they were already using v2.0.0 of `riak-common`: see [roles.txt](https://github.com/basho-labs/ansible-riak/blob/ea9902eb94bd5a44d8b729d1ff8460928b379569/examples/roles.txt).

In the case of the latter, how different should the cluster setup be from the "old" examples? Are there plans to release some cluster setup examples any time soon?

Thanks in advance.

**Comment by christophermancini** [comment]
Hi @jlbribeiro, they were deleted because they were outdated and I neglected to get the README updated which is on me. We are at our engineering all hands this week and I will see if we can't get an example for you with regards to using it for a cluster.

**Comment by jaytaylor** [comment]
+1 for inclusion of cluster setup instructions.

**Comment by christophermancini** [comment]
I will get it done this coming week

**Comment by jaytaylor** [comment]
Thanks for the quick response Chris, that would be amazing!

**Comment by christophermancini** [comment]
@jaytaylor @jlbribeiro let me know if this helps, #33

**Comment by jaytaylor** [comment]
This has some really helpful information, but I'm now getting an error since ansible isn't installed on the target systems:

    TASK: [ansible-riak | Fetch ansible ansible_version] **************************
    failed: [1.2.3.4] => {"cmd": "ansible --version", "failed": true, "rc": 2}
    msg: [Errno 2] No such file or directory

**Comment by jaytaylor** [comment]
Using the following seems to cause riak to complain and fail:

    - name: Join the cluster
      command: '{{ riak_admin }} join {{ ring_leader }}'

    - name: Check Riak Ring
      command: '{{ riak_admin }} cluster status'
      register: riak_ring_status

    - name: Plan the cluster
      command: '{{ riak_admin }} plan'
      when: riak_ring_status.stdout.find('joining') > 0

    - name: Commit the cluster
      command: '{{ riak_admin }} commit'
      when: riak_ring_status.stdout.find('joining') > 0


    failed: [1.2.3.4] => {"changed": true, "cmd": ["riak-admin", "join", "riak1@1.2.3.4"], "delta": "0:00:00.136772", "end": "2016-01-27 23:38:33.141225", "rc": 1, "start": "2016-01-27 23:38:33.004453", "warnings": []}
    stdout: The 'join' command has been deprecated in favor of the new
    clustering commands provided by 'riak-admin cluster'. To continue
    using the deprecated 'join' command, use 'join -f'

**Comment by christophermancini** [comment]
@jaytaylor Thanks for noticing that, I think it was my bad with a copy / paste error. I just pushed up a fix, using the cluster command.

**Comment by christophermancini** [comment]
Updated the README with new docs.
