### ISSUE TITLE
Readme is incorrect regarding riak ansible module

### ISSUE THREAD

**Issue by jsmartin** [basho-labs/ansible-riak#37]
The readme states that the riak ansible module is in extras so is not part of the core install.  That is incorrect.  A pip install, git install, or OS package install all currently provide the ansible-extras modules.  I find it a bit odd that the examples here show how to use the riak command line tools in preference of the riak ansible module, but perhaps it's because of this misunderstanding.

**Comment by christophermancini** [comment]
Thanks @jsmartin, it was because of this misunderstanding. I will update the README.

**Comment by christophermancini** [comment]
So, would you say then that the extras modules are available 99% of the time and can be relied upon or do I need to still offer an alternative or failsafe should they not be available?

**Comment by christophermancini** [comment]
Updated the README. Thanks for pointing that out @jsmartin

**Comment by jsmartin** [comment]
I can't see why they wouldn't be available.
