### ISSUE TITLE
Unable to install through Galaxy

### ISSUE THREAD

**Issue by Guibod** [basho-labs/ansible-riak#39]
Hi,

In the « Ansible Galaxy Install » readme section, references are made to christophermancini.riak-kv which no longer exists.

There is no basho-labs or riak roles that matches this repository on Ansible Galaxy anymore.
I'll clone the repository, but I think that worth an action on your side.

**Comment by lypht** [comment]
+1

**Comment by christophermancini** [comment]
Your right, its gone. I will investigate. Thanks for the heads up.

**Comment by christophermancini** [comment]
Again, thanks for the heads up. Ansible apparently upgraded the system to use the GH organization and apparently dropped the role from the database because it didn't match... I resubmitted the role and updated the README.

https://github.com/basho-labs/ansible-riak#ansible-galaxy-install
