### ISSUE TITLE
Debian doesn't support URL for package name.

### ISSUE THREAD

**Issue by drewkerrigan** [basho-labs/ansible-riak#40]
When attempting to reference a URL or file on the remote machine for `riak.deb`, ansible gives this message:

```
TASK [ansible-riak : Install Riak for Debian] **********************************
fatal: [54.194.64.222]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'http://s3.amazonaws.com/.../riak.deb' is available"}
```

It appears the cause of this is the fact that the apt module requires another parameter called `deb` when referencing local files. I'm not sure how to supply a URL at this point.

**Comment by christophermancini** [comment]
Fixed with #57
