### ISSUE TITLE
Using the a dependant package with ansible 2.0.1.0 and with_items

### ISSUE THREAD

**Issue by Guibod** [basho-labs/ansible-riak#48]
I have trouble making my `riak` role inherit this one with ansible 2.0.1.0.  The with_items don't work very nice with BARE variables (eg not inside a "{{…}}") that cause my playbook to crash on security.yml and buckets.yml

Would it be possible to change `security.yml` to something like that:

```
---
- name: Create users
  command: '{{ riak_admin }} security add-user {{ item.user }} password={{ item.password }}'
  with_items: "{{riak_users}}"

- name: Create security sources
  command: '{{ riak_admin }} security add-source {{ item.user }} {{ item.cidr }} {{ item.type }}'
  with_items: "{{ riak_sources }}"

- name: Set security permissions
  command: '{{ riak_admin }} security grant {{ item.permissions }} on {{ item.container }} to {{ item.subject }}'
  with_items: "{{ riak_grants }}"
```

This to avoid this kin d of message:

> [DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{riak_bucket_types}}'). This feature will be removed in a future release. Deprecation warnings can be disabled by 
> setting deprecation_warnings=False in ansible.cfg.

**Comment by christophermancini** [comment]
Hey @Guibod I actually had a pending PR ( #47 ) since last week to address the deprecation warnings. The PR was just merged, let me know if you still have any issues.

**Comment by Guibod** [comment]
That's ok right now, thanks.
