### ISSUE TITLE
Unecessary backup of files

### ISSUE THREAD

**Issue by jsmartin** [basho-labs/ansible-riak#56]
https://github.com/basho-labs/ansible-riak/blob/develop/tasks/main.yml#L45
https://github.com/basho-labs/ansible-riak/blob/develop/tasks/main.yml#L50

The template module has a "backup" parameter that will automatically backup and timestamp the file it replaces, should negate the need for these.

http://docs.ansible.com/ansible/template_module.html

**Comment by christophermancini** [comment]
Is that a new feature with 2.0 or has it been there for a while?

**Comment by jsmartin** [comment]
It's been around awhile, not sure exactly how long.

**Comment by christophermancini** [comment]
Updated in #57. If you could give it a glance, I would appreciate it.
