### ISSUE TITLE
Support runit in non-production environments

### ISSUE THREAD

**Issue by lucafavatella** [basho-labs/ansible-riak#70]
Developers using Docker for development/testing/staging environment (not for production) would benefit from using the same scripts for all environments. In Docker containers, alternative init systems are usually preferred to systemd - runit is one of those e.g. see https://github.com/phusion/baseimage-docker .

**Comment by christophermancini** [comment]
Hi @lucafavatella, I am not sure I want to open the door of offering full support for non-system default init systems. I think it is reasonable to add a var that allows the user to skip the standard OS init task. Then in your playbook, you can add whatever tasks are necessary for your desired init system. Thoughts?

**Comment by lucafavatella** [comment]
@christophermancini I totally agree with you in theory - I am not sure how that realizes in practice.
Would you mind drafting a change (branch) for skipping "the standard OS init task"? I would then happy to use it in my playbook.

My concern comes from the changes I identified in https://github.com/basho-labs/ansible-riak/pull/71/files . I need to avoid Ansible modules `service` and `systemd` for runit - and here my limited knowledge of Ansible does not help:
* Can a Ansible handler be made conditional? Otherwise I propose deleting `restart riak` handler altogether.
* File `tasks/main.yml` reboots riak - using `service` Ansible module - then waits for Riak to be up. How can `tasks/main.yml` conditionally delegate to the user one task (reboot) *in the middle of the file*?

**Comment by christophermancini** [comment]
@lucafavatella The handler is actually not even being used anymore, so I removed it in #74. I created a var, `riak_init_system` which defaults to `system`. If this var does not equal `system`, it will skip the reboot task via the service module.

This allows you to reboot Riak yourself within the `tasks` section of your playbook, which will execute after the roles section is completed.

**Comment by lucafavatella** [comment]
@christophermancini I managed to get back to this, sorry for the delay. Thanks for the change, it helped. I got two remaining issues for managing to use it:
* https://github.com/basho-labs/ansible-riak/pull/75 - fix in PR;
* Failed [waiting for Riak to come up after (non-)reboot](https://github.com/basho-labs/ansible-riak/blob/44f3312f0b9e8e0efadfd40fba8cdb35d831de8c/tasks/main.yml#L49) - not sure how to fix this yet.

**Comment by lucafavatella** [comment]
> Failed waiting for Riak to come up after (non-)reboot - not sure how to fix this yet.

I believe #76 fixes this - tested on local VM (was failing before).

**Comment by lucafavatella** [comment]
> I believe #76 fixes this - tested on local VM (was failing before).

I closed #76 - see https://github.com/basho-labs/ansible-riak/pull/76#issuecomment-290666450 for reason.

I suggest this ticket is closed after #75 is merged.

**Comment by lucafavatella** [comment]
#75 is merged. Closing this then.

See https://github.com/basho-labs/ansible-riak/pull/76#issuecomment-290666450 for runit support until Ansible matures in handlers/notify semantics.
