### ISSUE TITLE
Error deploying Riak KV with Ansible 2.2.2.0 inventory having group named `riak`

### ISSUE THREAD

**Issue by lucafavatella** [basho-labs/ansible-riak#79]
ansible-riak [defaults](
https://github.com/basho-labs/ansible-riak/blob/v2.3.0/defaults/main.yml#L49) `riak_shell_group` to `'riak'`. Apparently Ansible 2.2.2.0 changed somehow evaluation of conditionals and/or dict lookup compared to 2.2.1.0 - see #78. Therefore users with an Ansible inventory [with a host group named `riak`](https://github.com/basho-labs/ansible-riak/pull/78#issuecomment-292211336) [experiences error in dict lookup](https://github.com/basho-labs/ansible-riak/pull/78#issuecomment-292210638).

Workaround as a user is changing default `riak_shell_group` when using ansible-riak e.g. `{ role: ansible-riak, riak_shell_group: }`.

Proper fix would either:
* Investigate Ansible semantics and review `riak_shell_nodes` and dependent variables; or
* Conditionally default `riak_shell_group` to `'riak'` only if riak ts is being installed.

**Comment by christophermancini** [comment]
Thanks @lucafavatella
