### ISSUE TITLE
Ansible-riak seems to ignore mount point

### ISSUE THREAD

**Issue by ricardoekm** [basho-labs/ansible-riak#9]
Hi,
I'm trying to configure ansible-riak to use a separate volume for riak data. Although the ansible script correctly mounts the volume it seems to ignore it.

var.yml
---
riak_partition: '/dev/vdb'
riak_mountpoint: '/riak-data'
riak_tune_disks: yes
riak_physical_disks: '[vdb]'

df /riak-data
Filesystem     1K-blocks   Used Available Use% Mounted on
/dev/vdb        20642428 176064  19417788   1% /riak-data

df /var/lib/riak
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/vda1       41283904 1008184  38179116   3% /

May be the ansible script should change app.config data root to the mounted folder?

After a fresh install it points to:
{data_root, "/var/lib/riak/bitcask"}

**Comment by christophermancini** [comment]
This is pretty old and we just pushed out a new release, are you still struggling with this issue using the new role?
